### ISSUE TITLE
AttributeError: 'Entry' object has no attribute 'set_max_width_chars'

### ISSUE THREAD

**Issue by MajorLunaC** [jwagner/playitslowly#11]
I'm using Linux Mint 17.3 'Rosa' 64-bit, and I'm running into what seems to be the same problem on playitslowly 1.4.0 and 1.5.0 . I have python 3, but it's not using it for playitslowly, which I'm guessing why this error appears when I try to run it. It installs fine, as far as I can tell.

> 

$ playitslowly 
type 'exceptions.AttributeError'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/playitslowly/app.py", line 533, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/playitslowly/app.py", line 522, in main
    win = MainWindow(sink, config)
  File "/usr/local/lib/python2.7/dist-packages/playitslowly/app.py", line 121, in __init__
    self.speedchooser = myGtk.TextScaleReset(Gtk.Adjustment.new(1.00, 0.10, 4.0, 0.05, 0.05, 0))
  File "/usr/local/lib/python2.7/dist-packages/playitslowly/myGtk.py", line 312, in __init__
    TextScale.__init__(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/playitslowly/myGtk.py", line 287, in __init__
    self.entry.set_max_width_chars(self.size)
AttributeError: 'Entry' object has no attribute 'set_max_width_chars'

lunac ~ $ python
python      python2.7   python3.4   python3m    
python2     python3     python3.4m

**Comment by jwagner** [comment]
How did you install playitslowly? Which pygtk version are you using?

**Comment by MajorLunaC** [comment]
python-gtk2 is the only pygtk even available in the Software Manager. I manually installed playitslowly  1.5.0 via "python setup.py install". After it failed to run, I uninstalled it and just tried the one in the Software Manager, 1.4.0 , but it failed the same way.

**Comment by jwagner** [comment]
Well that should have been python3 setup.py install. Does that work?

If it didn't how did you uninstall it? And regarding the versions on python3 it's libgtk-3-0 and python3-gi.

**Comment by MajorLunaC** [comment]
python3 setup.py install does not help. I have a custom script to track the install, and according to its log, the only thing installed as root is /usr/local/bin/playitslowly
That same program removes all that was logged.
libgtk-3-0 and python3-gi are already installed.

**Comment by jwagner** [comment]
Again, please post the versions of  libgtk-3-0 and python3-gi.
Also post the output of ```python3 -c 'from gi.repository import Gtk;print(Gtk.get_major_version(), Gtk.get_minor_version())'```. It should be a recent version (3.16 or 3.18 should be fine).

**Comment by MajorLunaC** [comment]
Oh, you meant the minor versions. All I have are the bizarre package names they come with:
libgtk-3-0 version 3.10.8~8+qiana
python3-gi version 3.12.0-1ubuntu1

The command gives version 3.10 , yikes. Mint 17.x is based on ubuntu 14.04 , if that helps. I don't think just updating things in general will jump that many versions, but I can try that tomorrow (lots of upgrading I'm betting). I'm not too sure if I can upgrade it to that level without causing a dependency nightmare. :(

**Comment by jwagner** [comment]
> Mint 17.x is based on ubuntu 14.04

O_o  why would they do that? Anyways I might be able to handle that error in code. I pushed a possible workaround to master. Clone that and it might work (or not).

**Comment by MajorLunaC** [comment]
As to why, I think a focus on stability, and GTK3 has some unpleasant changes? Something like that. Better than Slackware that I switched from in Jan, which hasn't updated stable releases in 2 years (no precedent).

With the change, it runs, but freezes permanently and irreparably on several (important instances):
1) Speed (times) modification at any time.
2) Rewind button.
3) Dragging the playing position bar button.
4) Marking a Start Position and then an End Position and then pressing play, or doing so while playing.
5) Start Position (seconds) greater than the current playing position.
6) End Position (seconds) less than the current playing position, or being marked first.
7) Start Position (seconds) greater than the current End Position (seconds) (Probably, wasn't able to test this one)

Yeah, I know, a lot of this is more idiot-proofing, or in my case, accident-proofing. Needless to say, I don't think it worked quite as expected.

**Comment by jwagner** [comment]
Sounds like seeking gstreamer is broken with your setup for some reason. These things all work for me.
I don't want to spend hours tracking down why this doesn't work in this constellation. You could try me newer web based tool that does +/- the same thing (and sounds a lot better too): https://29a.ch/timestretch/

**Comment by MajorLunaC** [comment]
Yeah, probably best to just keep a version around until Mint catches up. The web version does work really well, although there is no way to save what you make.

I also noticed there is quite a difference between it and mplayer's way of doing it. Mplayer's way sounds almost jittery while the web one sounds fantastic, like playing in an amphitheater when slowed down. Do you use a filter or something, or is mplayer lacking something there?

mplayer -af scaletempo
(you need to get an mplayer which has the scaletempo filter)

mplayer -speed 1.5 -af ladspa=tap_pitch:tap_pitch:0:-33:-90:0 foo.avi
(might require installing the ladspa plugins)

Anyway, thanks for all the awesome help!

**Comment by jwagner** [comment]
> The web version does work really well, although there is no way to save what you make.
 I plan to add that. I just have a bit too many things to do right now. :)

> I also noticed there is quite a difference between it and mplayer's way of doing it. Mplayer's way sounds almost jittery while the web one sounds fantastic, like playing in an amphitheater when slowed down. Do you use a filter or something, or is mplayer lacking something there?

There is no obvious mathematically obvious way to do timestretching while keeping the pitch. So different algorithms create different artifacts. I chose to implement a fairly high quality algorithm for timestretching and tweaked it so the tradeoffs are acceptable for what I use it for (practicing music). It messes up the stereo image quite badly and sounds a bit diffuse but it keeps timbre and percusive hits mostly intact (other algorithms tend to double them which I find extremely annoying).

I'll close this ticket. For future readers: If you care about these compatibility issues feel free to fix them and send me a pullrequest. :)
