### ISSUE TITLE
Rename the app id

### ISSUE THREAD

**Issue by bochecha** [jwagner/playitslowly#17]
I'm working on packaging Play it Slowly as a [Flatpak](http://flatpak.org).

One thing that Flatpak enforces, is the usage of "reverse-DNS"-like application ids, of the form `$tld.$project.$AppName`, for example org.gnome.Polari.

This is a convention that helps ensures uniqueness: if the Bar and Baz projects both made an app named "Foo", it is still possible to distinguish org.bar.Foo from org.baz.Foo.

Enforcing this allows Flatpak to properly sandbox the applications, and export their resources to the outside.

So the first thing to do would be to choose such an application id for Play it Slowly. For example it could be as simple as org.playitslowly.PlayItSlowly. If Play it Slowly were part of a bigger umbrella project, then the second member could reflect that.

The application id passed to GtkApplication must be changed as well to correspond, but Play it Slowly doesn't use GtkApplication so there is nothing to do here.

Then, the icons, desktop and appdata files must all be named following this app id.

I'm happy to send a pull request that does the work, if you just tell me what name to use. 😃

**Comment by jwagner** [comment]
Hello Bochecha,

I'm not up to date anymore on what is going on with regards to Linux desktop applications but I guess that would be ch.29a.playitslowly then. I'm looking forward to your pull-request. 

Cheers,
Jonas

**Comment by bochecha** [comment]
Unfortunately, segments can't start with numbers.

**Comment by jwagner** [comment]
ch.x29a.playitslowlyit is then :)
