### ISSUE TITLE
Port to modern technologies

### ISSUE THREAD

**Issue by afranke** [jwagner/playitslowly#7]
It would be nice to have a modern version using GTK+ 3, GStreamer 1…

**Comment by jwagner** [comment]
Gave this a shot today. It was quite painful but I think it works now.

Cheers,
Jonas

**Comment by jwagner** [comment]
I released version 1.5 which is using python 3 gtk3 and gstreamer 1. :)

**Comment by afranke** [comment]
Awesome. "Funny" story: I wanted to try out master when you made the first comment two days ago, so I looked for a way to uninstall the version I had first. Since setup.py doesn't handle uninstall, I generated a list of installed files with setup.py (or so I thought) and then I ran `cat files.txt|xargs rm -rf` and my session went nuts. I then realised what was happening: it was running `rm -rf /` and my system was now completely broken.

I'll try 1.5 as soon as I can get my system back up and running. Thanks for your work on this!

**Comment by jwagner** [comment]
Ouch. I had a similar incident at one point running something like ``find -delete -iname *.pyc``. Deletes all the files and the prints out the ones that match *.pyc. Anyways there would have been a file containing all the files that were installed (for exactly that purpose): $PREFIX/lib/python3.4/dist-packages/playitslowly-py3.4.install-info.

Good luck with the recovery!

Cheers,
Jonas

**Comment by trebmuh** [comment]
Sweat, thanks Jonas !

**Comment by afranke** [comment]
Finally recovered and got the time to test. Looks great, works good so far. Thanks a lot!
