### ISSUE TITLE
Rewind regression

### ISSUE THREAD

**Issue by afranke** [jwagner/playitslowly#9]
In 1.5.0 when you set a different start position than 0 and you hit the rewind button, the current playing position goes back to 0 and not the set start position. When you hit play, the current playing position has to jump to the correct time and you can hear that jump.

**Comment by jwagner** [comment]
It probably behaved like this before too. Anyways, I fixed it. It's not seeking to start rather than 0. Thanks for letting me know! :)

**Comment by afranke** [comment]
Ah, it may have behaved like that, but maybe the jump was not as obvious with the old tech? Anyway thanks for the quick response!

**Comment by trebmuh** [comment]
Sweat, good catch @afranke and thank for the quick fix @jwagner.
